// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA05gmEG4Fc6ZxJo-XIdamtfS22-otX-PQ',
    appId: '1:581873853607:web:5a1af001f4f7ed71b0e782',
    messagingSenderId: '581873853607',
    projectId: 'oshiten-app',
    authDomain: 'oshiten-app.firebaseapp.com',
    storageBucket: 'oshiten-app.appspot.com',
    measurementId: 'G-D693X7JCKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJUSYG3SIVhjiMBa0rD4P2RdOuvfatUHc',
    appId: '1:581873853607:android:23bbfafaaaa8285ab0e782',
    messagingSenderId: '581873853607',
    projectId: 'oshiten-app',
    storageBucket: 'oshiten-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPeSVuRDqZSCq4hT6wQoFK1jSCaTyHDes',
    appId: '1:581873853607:ios:b3939da828570958b0e782',
    messagingSenderId: '581873853607',
    projectId: 'oshiten-app',
    storageBucket: 'oshiten-app.appspot.com',
    iosClientId: '581873853607-1m2bggvjl317a5jh2kce3kujl8jnp0ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.oshitenApp',
  );
}
